# Generated by Django 2.2 on 2019-04-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('br_id', models.AutoField(db_column='BR_ID', primary_key=True, serialize=False)),
                ('br_address', models.CharField(blank=True, db_column='BR_ADDRESS', max_length=60, null=True)),
                ('br_phone_num', models.CharField(blank=True, db_column='BR_PHONE_NUM', max_length=20, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cu_id', models.AutoField(db_column='CU_ID', primary_key=True, serialize=False)),
                ('cu_first_name', models.CharField(blank=True, db_column='CU_FIRST_NAME', max_length=20, null=True)),
                ('cu_last_name', models.CharField(blank=True, db_column='CU_LAST_NAME', max_length=20, null=True)),
                ('cu_phone_num', models.CharField(blank=True, db_column='CU_PHONE_NUM', max_length=20, null=True)),
                ('cu_address', models.CharField(blank=True, db_column='CU_ADDRESS', max_length=60, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('em_id', models.AutoField(db_column='EM_ID', primary_key=True, serialize=False)),
                ('em_first_name', models.CharField(blank=True, db_column='EM_FIRST_NAME', max_length=20, null=True)),
                ('em_last_name', models.CharField(blank=True, db_column='EM_LAST_NAME', max_length=20, null=True)),
                ('em_pay_rate', models.DecimalField(blank=True, db_column='EM_PAY_RATE', decimal_places=2, max_digits=5, null=True)),
                ('em_phone_num', models.CharField(blank=True, db_column='EM_PHONE_NUM', max_length=20, null=True)),
                ('em_dob', models.DateField(blank=True, db_column='EM_DOB', null=True)),
                ('em_ss_num', models.CharField(blank=True, db_column='EM_SS_NUM', max_length=20, null=True)),
                ('em_address', models.CharField(blank=True, db_column='EM_ADDRESS', max_length=40, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ma_id', models.AutoField(db_column='MA_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseHist',
            fields=[
                ('ph_id', models.AutoField(db_column='PH_ID', primary_key=True, serialize=False)),
                ('ph_date', models.DateField(blank=True, db_column='PH_DATE', null=True)),
                ('num_purchased', models.IntegerField(blank=True, db_column='NUM_PURCHASED', null=True)),
                ('ind_cost', models.DecimalField(blank=True, db_column='IND_COST', decimal_places=2, max_digits=5, null=True)),
                ('tot_cost', models.DecimalField(blank=True, db_column='TOT_COST', decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'purchase_hist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('re_id', models.AutoField(db_column='RE_ID', primary_key=True, serialize=False)),
                ('re_date', models.DateField(db_column='RE_DATE')),
                ('due_date', models.DateField(db_column='DUE_DATE')),
            ],
            options={
                'db_table': 'rental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentalHist',
            fields=[
                ('rh_id', models.AutoField(db_column='RH_ID', primary_key=True, serialize=False)),
                ('rh_date', models.DateField(blank=True, db_column='RH_DATE', null=True)),
            ],
            options={
                'db_table': 'rental_hist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('ve_id', models.AutoField(db_column='VE_ID', primary_key=True, serialize=False)),
                ('ve_name', models.CharField(blank=True, db_column='VE_NAME', max_length=40, null=True)),
                ('ve_phone_num', models.CharField(blank=True, db_column='VE_PHONE_NUM', max_length=20, null=True)),
                ('ve_address', models.CharField(blank=True, db_column='VE_ADDRESS', max_length=60, null=True)),
            ],
            options={
                'db_table': 'vendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('vg_id', models.AutoField(db_column='VG_ID', primary_key=True, serialize=False)),
                ('vg_name', models.CharField(blank=True, db_column='VG_NAME', max_length=40, null=True)),
                ('vg_genre', models.CharField(blank=True, db_column='VG_GENRE', max_length=20, null=True)),
                ('vg_publisher', models.CharField(blank=True, db_column='VG_PUBLISHER', max_length=40, null=True)),
                ('vg_copies_owned', models.IntegerField(blank=True, db_column='VG_COPIES_OWNED', null=True)),
                ('vg_copies_rented', models.IntegerField(blank=True, db_column='VG_COPIES_RENTED', null=True)),
            ],
            options={
                'db_table': 'video_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mockbuster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
